#!/bin/zsh
set -eu

script_dir=${0:A:h}
harness_root=${script_dir:h}
pi_binary=${HARNESS_PI_BINARY:-"$harness_root/node_modules/.bin/pi"}

if [[ ! -f "$pi_binary" ]]; then
  print -u2 "pi-reviewer-child: missing required resource: $pi_binary"
  exit 1
fi

unset \
  ORCA_AGENT_HOOK_ENDPOINT \
  ORCA_AGENT_HOOK_ENV \
  ORCA_AGENT_HOOK_PORT \
  ORCA_AGENT_HOOK_TOKEN \
  ORCA_AGENT_HOOK_VERSION \
  ORCA_AGENT_LAUNCH_TOKEN \
  ORCA_PANE_KEY \
  ORCA_PI_PREFILL \
  ORCA_PI_STATUS_OWNED \
  ORCA_TAB_ID \
  ORCA_TERMINAL_HANDLE \
  ORCA_WORKSPACE_ID \
  ORCA_WORKTREE_ID

exec "$pi_binary" "$@"
